#!/usr/bin/env bash
# transfer file to server.

usage(){
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if (( $# < 4 )); then
    usage
    exit
fi

scp -o "StrictHostKeyChecking No" -i "$4" "$3"@"$2":~/ "$1"
