#!/usr/bin/env bash
# Transfer file to server.

usage(){
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if (( $# < 3 )); then usage; exit
fi

scp -o StrictHostKeyChecking=No -i "$4" "$1" "$3"@"$2":~/
