#!/usr/bin/env bash
# Install nginx on remote server.

apt-key adv --fetch-keys https://nginx.org/keys/nginx_signing.key
echo "deb http://nginx.org/packages/ubuntu/ trusty nginx" >> /etc/apt/sources.list
echo "deb-src http://nginx.org/packages/ubuntu/ trusty nginx" >> /etc/apt/sources.list
apt-get -y update
apt-get -y install nginx
echo "Holberton School" | tee /usr/share/nginx/html/index.html
