#!/usr/bin/env bash
# Install nginx on remote server.
sudo apt-get -y update
sudo apt-get -y install nginx

# Edit config file to add a redirect page.
url="https://www.youtube.com/watch?v=QH2-TGUlwu4"
redirect="location /redirect_me { return 301 $url; }"
sudo sed -i "38i\\\t$redirect\n" /etc/nginx/sites-available/default

sudo service nginx start
