#!/usr/bin/env bash
# Install nginx on remote server.
sudo apt-get -y update
sudo apt-get -y install nginx

# Edit config file to add a redirect page.
redirect="location /redirect_me { rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }"
sudo sed -i "38i\\\t$redirect\n" /etc/nginx/sites-enabled/default

sudo service nginx start
