#!/usr/bin/env bash
# Change user of nginx.

useradd nginx
sed -i 's/www-data/nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
chown nginx /usr/sbin/nginx
service nginx restart
