#!/usr/bin/env bash
# Change user of nginx.
sed -i -e 's/listen 80/listen 8080/' -e 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default
chown -R nginx /etc/nginx/
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su nginx -c /usr/sbin/nginx
