#!/usr/bin/env bash
# Bash script solution for FizzBuzz

for i in {1..100}; do
    if ((i%3==0)); then printf "Fizz"; fi
    if ((i%5==0)); then printf "Buzz"; fi
    if ((i%3==0 || i%5==0)); then printf "\n"; else echo $i; fi
done
