#!/usr/bin/env bash
# Print 1 to 100, Fizz on multiples of 3, Buzz on multiples of 5
# and FizzBuzz on multiples of 3 and 5.

for i in {1..100}; do
    if ((i%3==0)); then printf "Fizz"; fi
    if ((i%5==0)); then printf "Buzz"; fi
    if ((i%3==0 || i%5==0)); then printf "\n"; else echo $i; fi
done
