#!/usr/bin/env bash
# Checks file using file test operators.

FILE="holbertonschool"
if [ -e $FILE ]; then
    echo $FILE file exists
    if [ ! -s $FILE ]; then
	echo $FILE file is empty
    else
	echo $FILE file is not empty
    fi
    if [ -f $FILE ]; then
	echo $FILE is a regular file
    else
	:
    fi
else
    echo $FILE file does not exist
fi
